### ISSUE TITLE
no such file or directory 

### ISSUE THREAD

**Issue by Oldlexar** [Valdex/b0mb3r#3]
Я знаю что ты знаешь русский поэтому реквест на русском
 services = os.listdir('services')
FileNotFoundError: [Errno 2] No such file or directory: 'services'

**Comment by Oldlexar** [comment]
чет совсем голова не варит, в общем я понял что у тебя огрызок, забудь

**Comment by Valdex** [comment]
где-то архив валяется в телеге, если найду то обновлю репу, но лучше какими-то другими бомберами воспользуйся, это тоже не оригинал
